// Code generated by protoc-gen-go. DO NOT EDIT.
// source: edge-cluster.proto

package edgecluster

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// The different error types
type Error int32

const (
	// Indicates the operation was successful
	Error_NO_ERROR Error = 0
	// Indicates the operation fail with unknown error
	Error_UNKNOWN Error = 1
	// Indicates the edge cluster already exists
	Error_EDGE_CLUSTER_ALREADY_EXISTS Error = 2
	// Indicates the edge cluster does not exist
	Error_EDGE_CLUSTER_NOT_FOUND Error = 3
	// Indicates the provided values for he operation were invalid
	Error_BAD_REQUEST Error = 4
)

var Error_name = map[int32]string{
	0: "NO_ERROR",
	1: "UNKNOWN",
	2: "EDGE_CLUSTER_ALREADY_EXISTS",
	3: "EDGE_CLUSTER_NOT_FOUND",
	4: "BAD_REQUEST",
}

var Error_value = map[string]int32{
	"NO_ERROR":                    0,
	"UNKNOWN":                     1,
	"EDGE_CLUSTER_ALREADY_EXISTS": 2,
	"EDGE_CLUSTER_NOT_FOUND":      3,
	"BAD_REQUEST":                 4,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}

func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_be558aad5309a67f, []int{0}
}

//*
// The edge cluster object
type EdgeCluster struct {
	// The edge cluster name
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EdgeCluster) Reset()         { *m = EdgeCluster{} }
func (m *EdgeCluster) String() string { return proto.CompactTextString(m) }
func (*EdgeCluster) ProtoMessage()    {}
func (*EdgeCluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_be558aad5309a67f, []int{0}
}

func (m *EdgeCluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EdgeCluster.Unmarshal(m, b)
}
func (m *EdgeCluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EdgeCluster.Marshal(b, m, deterministic)
}
func (m *EdgeCluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EdgeCluster.Merge(m, src)
}
func (m *EdgeCluster) XXX_Size() int {
	return xxx_messageInfo_EdgeCluster.Size(m)
}
func (m *EdgeCluster) XXX_DiscardUnknown() {
	xxx_messageInfo_EdgeCluster.DiscardUnknown(m)
}

var xxx_messageInfo_EdgeCluster proto.InternalMessageInfo

func (m *EdgeCluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//*
// Request to create a new edge cluster
type CreateEdgeClusterRequest struct {
	// The unique tenant identifier
	TenantID string `protobuf:"bytes,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	// The edge cluster object
	EdgeCluster          *EdgeCluster `protobuf:"bytes,2,opt,name=edgeCluster,proto3" json:"edgeCluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateEdgeClusterRequest) Reset()         { *m = CreateEdgeClusterRequest{} }
func (m *CreateEdgeClusterRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEdgeClusterRequest) ProtoMessage()    {}
func (*CreateEdgeClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be558aad5309a67f, []int{1}
}

func (m *CreateEdgeClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEdgeClusterRequest.Unmarshal(m, b)
}
func (m *CreateEdgeClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEdgeClusterRequest.Marshal(b, m, deterministic)
}
func (m *CreateEdgeClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEdgeClusterRequest.Merge(m, src)
}
func (m *CreateEdgeClusterRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEdgeClusterRequest.Size(m)
}
func (m *CreateEdgeClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEdgeClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEdgeClusterRequest proto.InternalMessageInfo

func (m *CreateEdgeClusterRequest) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

func (m *CreateEdgeClusterRequest) GetEdgeCluster() *EdgeCluster {
	if m != nil {
		return m.EdgeCluster
	}
	return nil
}

//*
// Response contains the result of creating a new edge cluster
type CreateEdgeClusterResponse struct {
	// Indicate whether the operation has any error
	Error Error `protobuf:"varint,1,opt,name=error,proto3,enum=edgecluster.Error" json:"error,omitempty"`
	// Contains error message if the operation was unsuccessful
	ErrorMessage string `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	// The unique edge cluster identifier
	EdgeClusterID        string   `protobuf:"bytes,3,opt,name=edgeClusterID,proto3" json:"edgeClusterID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateEdgeClusterResponse) Reset()         { *m = CreateEdgeClusterResponse{} }
func (m *CreateEdgeClusterResponse) String() string { return proto.CompactTextString(m) }
func (*CreateEdgeClusterResponse) ProtoMessage()    {}
func (*CreateEdgeClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be558aad5309a67f, []int{2}
}

func (m *CreateEdgeClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEdgeClusterResponse.Unmarshal(m, b)
}
func (m *CreateEdgeClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEdgeClusterResponse.Marshal(b, m, deterministic)
}
func (m *CreateEdgeClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEdgeClusterResponse.Merge(m, src)
}
func (m *CreateEdgeClusterResponse) XXX_Size() int {
	return xxx_messageInfo_CreateEdgeClusterResponse.Size(m)
}
func (m *CreateEdgeClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEdgeClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEdgeClusterResponse proto.InternalMessageInfo

func (m *CreateEdgeClusterResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NO_ERROR
}

func (m *CreateEdgeClusterResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *CreateEdgeClusterResponse) GetEdgeClusterID() string {
	if m != nil {
		return m.EdgeClusterID
	}
	return ""
}

//* Request to read an existing edge cluster
type ReadEdgeClusterRequest struct {
	// The unique tenant identifier
	TenantID string `protobuf:"bytes,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	// The unique edge cluster identifier
	EdgeClusterID        string   `protobuf:"bytes,2,opt,name=edgeClusterID,proto3" json:"edgeClusterID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadEdgeClusterRequest) Reset()         { *m = ReadEdgeClusterRequest{} }
func (m *ReadEdgeClusterRequest) String() string { return proto.CompactTextString(m) }
func (*ReadEdgeClusterRequest) ProtoMessage()    {}
func (*ReadEdgeClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be558aad5309a67f, []int{3}
}

func (m *ReadEdgeClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadEdgeClusterRequest.Unmarshal(m, b)
}
func (m *ReadEdgeClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadEdgeClusterRequest.Marshal(b, m, deterministic)
}
func (m *ReadEdgeClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadEdgeClusterRequest.Merge(m, src)
}
func (m *ReadEdgeClusterRequest) XXX_Size() int {
	return xxx_messageInfo_ReadEdgeClusterRequest.Size(m)
}
func (m *ReadEdgeClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadEdgeClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadEdgeClusterRequest proto.InternalMessageInfo

func (m *ReadEdgeClusterRequest) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

func (m *ReadEdgeClusterRequest) GetEdgeClusterID() string {
	if m != nil {
		return m.EdgeClusterID
	}
	return ""
}

//*
// Response contains the result of reading an existing edge cluster
type ReadEdgeClusterResponse struct {
	// Indicate whether the operation has any error
	Error Error `protobuf:"varint,1,opt,name=error,proto3,enum=edgecluster.Error" json:"error,omitempty"`
	// Contains error message if the operation was unsuccessful
	ErrorMessage string `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	// The edge cluster object
	EdgeCluster          *EdgeCluster `protobuf:"bytes,3,opt,name=edgeCluster,proto3" json:"edgeCluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReadEdgeClusterResponse) Reset()         { *m = ReadEdgeClusterResponse{} }
func (m *ReadEdgeClusterResponse) String() string { return proto.CompactTextString(m) }
func (*ReadEdgeClusterResponse) ProtoMessage()    {}
func (*ReadEdgeClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be558aad5309a67f, []int{4}
}

func (m *ReadEdgeClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadEdgeClusterResponse.Unmarshal(m, b)
}
func (m *ReadEdgeClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadEdgeClusterResponse.Marshal(b, m, deterministic)
}
func (m *ReadEdgeClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadEdgeClusterResponse.Merge(m, src)
}
func (m *ReadEdgeClusterResponse) XXX_Size() int {
	return xxx_messageInfo_ReadEdgeClusterResponse.Size(m)
}
func (m *ReadEdgeClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadEdgeClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadEdgeClusterResponse proto.InternalMessageInfo

func (m *ReadEdgeClusterResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NO_ERROR
}

func (m *ReadEdgeClusterResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *ReadEdgeClusterResponse) GetEdgeCluster() *EdgeCluster {
	if m != nil {
		return m.EdgeCluster
	}
	return nil
}

//*
// Request to update an existing edge cluster
type UpdateEdgeClusterRequest struct {
	// The unique tenant identifier
	TenantID string `protobuf:"bytes,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	// The unique edge cluster identifier
	EdgeClusterID string `protobuf:"bytes,2,opt,name=edgeClusterID,proto3" json:"edgeClusterID,omitempty"`
	// The edge cluster object contains the updated edge cluster details to update
	EdgeCluster          *EdgeCluster `protobuf:"bytes,3,opt,name=edgeCluster,proto3" json:"edgeCluster,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateEdgeClusterRequest) Reset()         { *m = UpdateEdgeClusterRequest{} }
func (m *UpdateEdgeClusterRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEdgeClusterRequest) ProtoMessage()    {}
func (*UpdateEdgeClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be558aad5309a67f, []int{5}
}

func (m *UpdateEdgeClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEdgeClusterRequest.Unmarshal(m, b)
}
func (m *UpdateEdgeClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEdgeClusterRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEdgeClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEdgeClusterRequest.Merge(m, src)
}
func (m *UpdateEdgeClusterRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEdgeClusterRequest.Size(m)
}
func (m *UpdateEdgeClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEdgeClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEdgeClusterRequest proto.InternalMessageInfo

func (m *UpdateEdgeClusterRequest) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

func (m *UpdateEdgeClusterRequest) GetEdgeClusterID() string {
	if m != nil {
		return m.EdgeClusterID
	}
	return ""
}

func (m *UpdateEdgeClusterRequest) GetEdgeCluster() *EdgeCluster {
	if m != nil {
		return m.EdgeCluster
	}
	return nil
}

//*
// Response contains the result of updating an existing edge cluster
type UpdateEdgeClusterResponse struct {
	// Indicate whether the operation has any error
	Error Error `protobuf:"varint,1,opt,name=error,proto3,enum=edgecluster.Error" json:"error,omitempty"`
	// Contains error message if the operation was unsuccessful
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEdgeClusterResponse) Reset()         { *m = UpdateEdgeClusterResponse{} }
func (m *UpdateEdgeClusterResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateEdgeClusterResponse) ProtoMessage()    {}
func (*UpdateEdgeClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be558aad5309a67f, []int{6}
}

func (m *UpdateEdgeClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEdgeClusterResponse.Unmarshal(m, b)
}
func (m *UpdateEdgeClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEdgeClusterResponse.Marshal(b, m, deterministic)
}
func (m *UpdateEdgeClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEdgeClusterResponse.Merge(m, src)
}
func (m *UpdateEdgeClusterResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateEdgeClusterResponse.Size(m)
}
func (m *UpdateEdgeClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEdgeClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEdgeClusterResponse proto.InternalMessageInfo

func (m *UpdateEdgeClusterResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NO_ERROR
}

func (m *UpdateEdgeClusterResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

//*
// Request to delete an existing edge cluster
type DeleteEdgeClusterRequest struct {
	// The unique tenant identifier
	TenantID string `protobuf:"bytes,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	// The unique edge cluster identifier
	EdgeClusterID        string   `protobuf:"bytes,2,opt,name=edgeClusterID,proto3" json:"edgeClusterID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEdgeClusterRequest) Reset()         { *m = DeleteEdgeClusterRequest{} }
func (m *DeleteEdgeClusterRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteEdgeClusterRequest) ProtoMessage()    {}
func (*DeleteEdgeClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_be558aad5309a67f, []int{7}
}

func (m *DeleteEdgeClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEdgeClusterRequest.Unmarshal(m, b)
}
func (m *DeleteEdgeClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEdgeClusterRequest.Marshal(b, m, deterministic)
}
func (m *DeleteEdgeClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEdgeClusterRequest.Merge(m, src)
}
func (m *DeleteEdgeClusterRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteEdgeClusterRequest.Size(m)
}
func (m *DeleteEdgeClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEdgeClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEdgeClusterRequest proto.InternalMessageInfo

func (m *DeleteEdgeClusterRequest) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

func (m *DeleteEdgeClusterRequest) GetEdgeClusterID() string {
	if m != nil {
		return m.EdgeClusterID
	}
	return ""
}

//*
// Response contains the result of deleting an existing edge cluster
type DeleteEdgeClusterResponse struct {
	// Indicate whether the operation has any error
	Error Error `protobuf:"varint,1,opt,name=error,proto3,enum=edgecluster.Error" json:"error,omitempty"`
	// Contains error message if the operation was unsuccessful
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteEdgeClusterResponse) Reset()         { *m = DeleteEdgeClusterResponse{} }
func (m *DeleteEdgeClusterResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteEdgeClusterResponse) ProtoMessage()    {}
func (*DeleteEdgeClusterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_be558aad5309a67f, []int{8}
}

func (m *DeleteEdgeClusterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteEdgeClusterResponse.Unmarshal(m, b)
}
func (m *DeleteEdgeClusterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteEdgeClusterResponse.Marshal(b, m, deterministic)
}
func (m *DeleteEdgeClusterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteEdgeClusterResponse.Merge(m, src)
}
func (m *DeleteEdgeClusterResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteEdgeClusterResponse.Size(m)
}
func (m *DeleteEdgeClusterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteEdgeClusterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteEdgeClusterResponse proto.InternalMessageInfo

func (m *DeleteEdgeClusterResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_NO_ERROR
}

func (m *DeleteEdgeClusterResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("edgecluster.Error", Error_name, Error_value)
	proto.RegisterType((*EdgeCluster)(nil), "edgecluster.EdgeCluster")
	proto.RegisterType((*CreateEdgeClusterRequest)(nil), "edgecluster.CreateEdgeClusterRequest")
	proto.RegisterType((*CreateEdgeClusterResponse)(nil), "edgecluster.CreateEdgeClusterResponse")
	proto.RegisterType((*ReadEdgeClusterRequest)(nil), "edgecluster.ReadEdgeClusterRequest")
	proto.RegisterType((*ReadEdgeClusterResponse)(nil), "edgecluster.ReadEdgeClusterResponse")
	proto.RegisterType((*UpdateEdgeClusterRequest)(nil), "edgecluster.UpdateEdgeClusterRequest")
	proto.RegisterType((*UpdateEdgeClusterResponse)(nil), "edgecluster.UpdateEdgeClusterResponse")
	proto.RegisterType((*DeleteEdgeClusterRequest)(nil), "edgecluster.DeleteEdgeClusterRequest")
	proto.RegisterType((*DeleteEdgeClusterResponse)(nil), "edgecluster.DeleteEdgeClusterResponse")
}

func init() { proto.RegisterFile("edge-cluster.proto", fileDescriptor_be558aad5309a67f) }

var fileDescriptor_be558aad5309a67f = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x49, 0x0b, 0xed, 0xb8, 0x50, 0x67, 0x0e, 0xc5, 0x0d, 0x07, 0x8a, 0x29, 0x28, 0x42,
	0x22, 0x87, 0x70, 0xe3, 0x16, 0xe2, 0x05, 0x45, 0x14, 0x5b, 0xac, 0x6d, 0xf1, 0xa1, 0x4a, 0x96,
	0x5d, 0x8f, 0xa2, 0x4a, 0xc5, 0x36, 0x6b, 0x97, 0xbf, 0xc1, 0x95, 0x13, 0x17, 0xfe, 0x28, 0xca,
	0xc6, 0x42, 0xfe, 0x04, 0xa2, 0xca, 0xb7, 0xdd, 0xc9, 0x9b, 0xf7, 0xe6, 0xcd, 0xce, 0xc4, 0x80,
	0x14, 0xad, 0xe8, 0xf9, 0xc5, 0xd5, 0x75, 0x96, 0x93, 0x98, 0xa6, 0x22, 0xc9, 0x13, 0x54, 0xd7,
	0xb1, 0x22, 0x64, 0x3c, 0x02, 0x95, 0x45, 0x2b, 0x5a, 0x6c, 0xae, 0x88, 0xb0, 0x13, 0x07, 0x5f,
	0x48, 0x57, 0x4e, 0x94, 0xc9, 0x3e, 0x97, 0x67, 0x43, 0x80, 0xbe, 0x10, 0x14, 0xe4, 0x54, 0x02,
	0x72, 0xfa, 0x7a, 0x4d, 0x59, 0x8e, 0x63, 0xd8, 0xcb, 0x29, 0x0e, 0xe2, 0x7c, 0x69, 0x16, 0x39,
	0x7f, 0xee, 0xf8, 0x12, 0xa4, 0x52, 0x91, 0xa1, 0x0f, 0x4e, 0x94, 0x89, 0x3a, 0xd3, 0xa7, 0x25,
	0xf5, 0x69, 0x99, 0xb1, 0x0c, 0x36, 0xbe, 0x2b, 0x70, 0xdc, 0x22, 0x9a, 0xa5, 0x49, 0x9c, 0x11,
	0x4e, 0x60, 0x97, 0x84, 0x48, 0x84, 0x94, 0xbc, 0x37, 0xc3, 0x2a, 0xe7, 0xfa, 0x17, 0xbe, 0x01,
	0xa0, 0x01, 0x07, 0xf2, 0xf0, 0x8e, 0xb2, 0x2c, 0x58, 0x91, 0x2c, 0x62, 0x9f, 0x57, 0x62, 0x78,
	0x0a, 0x77, 0x4b, 0xd2, 0x4b, 0x53, 0x1f, 0x4a, 0x50, 0x35, 0x68, 0x7c, 0x86, 0x23, 0x4e, 0x41,
	0xb4, 0x65, 0x0f, 0x1a, 0xdc, 0x83, 0x36, 0xee, 0x5f, 0x0a, 0xdc, 0x6f, 0x90, 0xf7, 0xe2, 0xb5,
	0xf6, 0x26, 0xc3, 0x6d, 0xde, 0xe4, 0x87, 0x02, 0xba, 0x97, 0x46, 0xdb, 0x0f, 0xc2, 0x7f, 0x35,
	0xe1, 0x46, 0xa5, 0x5d, 0xc2, 0x71, 0x4b, 0x65, 0x7d, 0x74, 0xd0, 0x38, 0x07, 0xdd, 0xa4, 0x2b,
	0xea, 0xa7, 0x09, 0x6b, 0x23, 0x2d, 0xec, 0x7d, 0x18, 0x79, 0x96, 0xc2, 0xae, 0xcc, 0xc1, 0x03,
	0xd8, 0xb3, 0x6c, 0x9f, 0x71, 0x6e, 0x73, 0xed, 0x16, 0xaa, 0x70, 0xc7, 0xb3, 0xde, 0x5a, 0xf6,
	0x07, 0x4b, 0x53, 0xf0, 0x21, 0x3c, 0x60, 0xe6, 0x1b, 0xe6, 0x2f, 0xce, 0x3c, 0xc7, 0x65, 0xdc,
	0x9f, 0x9f, 0x71, 0x36, 0x37, 0x3f, 0xf9, 0xec, 0xe3, 0xd2, 0x71, 0x1d, 0x6d, 0x80, 0x63, 0x38,
	0xaa, 0x00, 0x2c, 0xdb, 0xf5, 0x5f, 0xdb, 0x9e, 0x65, 0x6a, 0x43, 0x3c, 0x04, 0xf5, 0xd5, 0xdc,
	0xf4, 0x39, 0x7b, 0xef, 0x31, 0xc7, 0xd5, 0x76, 0x66, 0x3f, 0x87, 0x80, 0x25, 0x5f, 0x0e, 0x89,
	0x6f, 0x97, 0x17, 0x84, 0x21, 0x8c, 0x1a, 0xab, 0x8e, 0x4f, 0x2a, 0xe6, 0xba, 0xfe, 0x7f, 0xc6,
	0x4f, 0xff, 0x05, 0x2b, 0x5a, 0x77, 0x0e, 0x87, 0xb5, 0x05, 0xc3, 0xc7, 0x95, 0xd4, 0xf6, 0xdd,
	0x1e, 0x9f, 0xfe, 0x1d, 0x54, 0xb0, 0x87, 0x30, 0x6a, 0x8c, 0x5f, 0xcd, 0x41, 0xd7, 0xe2, 0xd4,
	0x1c, 0x74, 0x4f, 0x71, 0x08, 0xa3, 0xc6, 0x64, 0xd4, 0x34, 0xba, 0xe6, 0xb2, 0xa6, 0xd1, 0x39,
	0x60, 0xe1, 0x6d, 0xf9, 0x81, 0x78, 0xf1, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x09, 0xf4, 0xaf, 0xe7,
	0x36, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EdgeClusterServiceClient is the client API for EdgeClusterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EdgeClusterServiceClient interface {
	// CreateEdgeCluster creates a new edge cluster
	// request: The request to create a new edge cluster
	// Returns the result of creating new edge cluster
	CreateEdgeCluster(ctx context.Context, in *CreateEdgeClusterRequest, opts ...grpc.CallOption) (*CreateEdgeClusterResponse, error)
	// ReadEdgeCluster read an exsiting edge cluster
	// request: The request to read an esiting edge cluster
	// Returns the result of reading an exiting edge cluster
	ReadEdgeCluster(ctx context.Context, in *ReadEdgeClusterRequest, opts ...grpc.CallOption) (*ReadEdgeClusterResponse, error)
	// UpdateEdgeCluster update an exsiting edge cluster
	// request: The request to update an esiting edge cluster
	// Returns the result of updateing an exiting edge cluster
	UpdateEdgeCluster(ctx context.Context, in *UpdateEdgeClusterRequest, opts ...grpc.CallOption) (*UpdateEdgeClusterResponse, error)
	// DeleteEdgeCluster delete an exsiting edge cluster
	// request: The request to delete an esiting edge cluster
	// Returns the result of deleting an exiting edge cluster
	DeleteEdgeCluster(ctx context.Context, in *DeleteEdgeClusterRequest, opts ...grpc.CallOption) (*DeleteEdgeClusterResponse, error)
}

type edgeClusterServiceClient struct {
	cc *grpc.ClientConn
}

func NewEdgeClusterServiceClient(cc *grpc.ClientConn) EdgeClusterServiceClient {
	return &edgeClusterServiceClient{cc}
}

func (c *edgeClusterServiceClient) CreateEdgeCluster(ctx context.Context, in *CreateEdgeClusterRequest, opts ...grpc.CallOption) (*CreateEdgeClusterResponse, error) {
	out := new(CreateEdgeClusterResponse)
	err := c.cc.Invoke(ctx, "/edgecluster.EdgeClusterService/CreateEdgeCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeClusterServiceClient) ReadEdgeCluster(ctx context.Context, in *ReadEdgeClusterRequest, opts ...grpc.CallOption) (*ReadEdgeClusterResponse, error) {
	out := new(ReadEdgeClusterResponse)
	err := c.cc.Invoke(ctx, "/edgecluster.EdgeClusterService/ReadEdgeCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeClusterServiceClient) UpdateEdgeCluster(ctx context.Context, in *UpdateEdgeClusterRequest, opts ...grpc.CallOption) (*UpdateEdgeClusterResponse, error) {
	out := new(UpdateEdgeClusterResponse)
	err := c.cc.Invoke(ctx, "/edgecluster.EdgeClusterService/UpdateEdgeCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeClusterServiceClient) DeleteEdgeCluster(ctx context.Context, in *DeleteEdgeClusterRequest, opts ...grpc.CallOption) (*DeleteEdgeClusterResponse, error) {
	out := new(DeleteEdgeClusterResponse)
	err := c.cc.Invoke(ctx, "/edgecluster.EdgeClusterService/DeleteEdgeCluster", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeClusterServiceServer is the server API for EdgeClusterService service.
type EdgeClusterServiceServer interface {
	// CreateEdgeCluster creates a new edge cluster
	// request: The request to create a new edge cluster
	// Returns the result of creating new edge cluster
	CreateEdgeCluster(context.Context, *CreateEdgeClusterRequest) (*CreateEdgeClusterResponse, error)
	// ReadEdgeCluster read an exsiting edge cluster
	// request: The request to read an esiting edge cluster
	// Returns the result of reading an exiting edge cluster
	ReadEdgeCluster(context.Context, *ReadEdgeClusterRequest) (*ReadEdgeClusterResponse, error)
	// UpdateEdgeCluster update an exsiting edge cluster
	// request: The request to update an esiting edge cluster
	// Returns the result of updateing an exiting edge cluster
	UpdateEdgeCluster(context.Context, *UpdateEdgeClusterRequest) (*UpdateEdgeClusterResponse, error)
	// DeleteEdgeCluster delete an exsiting edge cluster
	// request: The request to delete an esiting edge cluster
	// Returns the result of deleting an exiting edge cluster
	DeleteEdgeCluster(context.Context, *DeleteEdgeClusterRequest) (*DeleteEdgeClusterResponse, error)
}

// UnimplementedEdgeClusterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEdgeClusterServiceServer struct {
}

func (*UnimplementedEdgeClusterServiceServer) CreateEdgeCluster(ctx context.Context, req *CreateEdgeClusterRequest) (*CreateEdgeClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEdgeCluster not implemented")
}
func (*UnimplementedEdgeClusterServiceServer) ReadEdgeCluster(ctx context.Context, req *ReadEdgeClusterRequest) (*ReadEdgeClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadEdgeCluster not implemented")
}
func (*UnimplementedEdgeClusterServiceServer) UpdateEdgeCluster(ctx context.Context, req *UpdateEdgeClusterRequest) (*UpdateEdgeClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEdgeCluster not implemented")
}
func (*UnimplementedEdgeClusterServiceServer) DeleteEdgeCluster(ctx context.Context, req *DeleteEdgeClusterRequest) (*DeleteEdgeClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEdgeCluster not implemented")
}

func RegisterEdgeClusterServiceServer(s *grpc.Server, srv EdgeClusterServiceServer) {
	s.RegisterService(&_EdgeClusterService_serviceDesc, srv)
}

func _EdgeClusterService_CreateEdgeCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEdgeClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeClusterServiceServer).CreateEdgeCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgecluster.EdgeClusterService/CreateEdgeCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeClusterServiceServer).CreateEdgeCluster(ctx, req.(*CreateEdgeClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeClusterService_ReadEdgeCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadEdgeClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeClusterServiceServer).ReadEdgeCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgecluster.EdgeClusterService/ReadEdgeCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeClusterServiceServer).ReadEdgeCluster(ctx, req.(*ReadEdgeClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeClusterService_UpdateEdgeCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEdgeClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeClusterServiceServer).UpdateEdgeCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgecluster.EdgeClusterService/UpdateEdgeCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeClusterServiceServer).UpdateEdgeCluster(ctx, req.(*UpdateEdgeClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeClusterService_DeleteEdgeCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEdgeClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeClusterServiceServer).DeleteEdgeCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/edgecluster.EdgeClusterService/DeleteEdgeCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeClusterServiceServer).DeleteEdgeCluster(ctx, req.(*DeleteEdgeClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EdgeClusterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "edgecluster.EdgeClusterService",
	HandlerType: (*EdgeClusterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEdgeCluster",
			Handler:    _EdgeClusterService_CreateEdgeCluster_Handler,
		},
		{
			MethodName: "ReadEdgeCluster",
			Handler:    _EdgeClusterService_ReadEdgeCluster_Handler,
		},
		{
			MethodName: "UpdateEdgeCluster",
			Handler:    _EdgeClusterService_UpdateEdgeCluster_Handler,
		},
		{
			MethodName: "DeleteEdgeCluster",
			Handler:    _EdgeClusterService_DeleteEdgeCluster_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "edge-cluster.proto",
}
