{{- if .Values.clusterRoleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "edge-cluster.clusterRoleBindingName" . }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "edge-cluster.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "edge-cluster.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}

