// Code generated by MockGen. DO NOT EDIT.
// Source: services/endpoint/contract.go

// Package mock_endpoint is a generated GoMock package.
package mock_endpoint

import (
	reflect "reflect"

	endpoint "github.com/go-kit/kit/endpoint"
	gomock "github.com/golang/mock/gomock"
)

// MockEndpointCreatorContract is a mock of EndpointCreatorContract interface.
type MockEndpointCreatorContract struct {
	ctrl     *gomock.Controller
	recorder *MockEndpointCreatorContractMockRecorder
}

// MockEndpointCreatorContractMockRecorder is the mock recorder for MockEndpointCreatorContract.
type MockEndpointCreatorContractMockRecorder struct {
	mock *MockEndpointCreatorContract
}

// NewMockEndpointCreatorContract creates a new mock instance.
func NewMockEndpointCreatorContract(ctrl *gomock.Controller) *MockEndpointCreatorContract {
	mock := &MockEndpointCreatorContract{ctrl: ctrl}
	mock.recorder = &MockEndpointCreatorContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEndpointCreatorContract) EXPECT() *MockEndpointCreatorContractMockRecorder {
	return m.recorder
}

// CreateEdgeClusterEndpoint mocks base method.
func (m *MockEndpointCreatorContract) CreateEdgeClusterEndpoint() endpoint.Endpoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEdgeClusterEndpoint")
	ret0, _ := ret[0].(endpoint.Endpoint)
	return ret0
}

// CreateEdgeClusterEndpoint indicates an expected call of CreateEdgeClusterEndpoint.
func (mr *MockEndpointCreatorContractMockRecorder) CreateEdgeClusterEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEdgeClusterEndpoint", reflect.TypeOf((*MockEndpointCreatorContract)(nil).CreateEdgeClusterEndpoint))
}

// DeleteEdgeClusterEndpoint mocks base method.
func (m *MockEndpointCreatorContract) DeleteEdgeClusterEndpoint() endpoint.Endpoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEdgeClusterEndpoint")
	ret0, _ := ret[0].(endpoint.Endpoint)
	return ret0
}

// DeleteEdgeClusterEndpoint indicates an expected call of DeleteEdgeClusterEndpoint.
func (mr *MockEndpointCreatorContractMockRecorder) DeleteEdgeClusterEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEdgeClusterEndpoint", reflect.TypeOf((*MockEndpointCreatorContract)(nil).DeleteEdgeClusterEndpoint))
}

// ListEdgeClusterNodesEndpoint mocks base method.
func (m *MockEndpointCreatorContract) ListEdgeClusterNodesEndpoint() endpoint.Endpoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEdgeClusterNodesEndpoint")
	ret0, _ := ret[0].(endpoint.Endpoint)
	return ret0
}

// ListEdgeClusterNodesEndpoint indicates an expected call of ListEdgeClusterNodesEndpoint.
func (mr *MockEndpointCreatorContractMockRecorder) ListEdgeClusterNodesEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEdgeClusterNodesEndpoint", reflect.TypeOf((*MockEndpointCreatorContract)(nil).ListEdgeClusterNodesEndpoint))
}

// ListEdgeClusterPodsEndpoint mocks base method.
func (m *MockEndpointCreatorContract) ListEdgeClusterPodsEndpoint() endpoint.Endpoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEdgeClusterPodsEndpoint")
	ret0, _ := ret[0].(endpoint.Endpoint)
	return ret0
}

// ListEdgeClusterPodsEndpoint indicates an expected call of ListEdgeClusterPodsEndpoint.
func (mr *MockEndpointCreatorContractMockRecorder) ListEdgeClusterPodsEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEdgeClusterPodsEndpoint", reflect.TypeOf((*MockEndpointCreatorContract)(nil).ListEdgeClusterPodsEndpoint))
}

// ListEdgeClusterServicesEndpoint mocks base method.
func (m *MockEndpointCreatorContract) ListEdgeClusterServicesEndpoint() endpoint.Endpoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEdgeClusterServicesEndpoint")
	ret0, _ := ret[0].(endpoint.Endpoint)
	return ret0
}

// ListEdgeClusterServicesEndpoint indicates an expected call of ListEdgeClusterServicesEndpoint.
func (mr *MockEndpointCreatorContractMockRecorder) ListEdgeClusterServicesEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEdgeClusterServicesEndpoint", reflect.TypeOf((*MockEndpointCreatorContract)(nil).ListEdgeClusterServicesEndpoint))
}

// ListEdgeClustersEndpoint mocks base method.
func (m *MockEndpointCreatorContract) ListEdgeClustersEndpoint() endpoint.Endpoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEdgeClustersEndpoint")
	ret0, _ := ret[0].(endpoint.Endpoint)
	return ret0
}

// ListEdgeClustersEndpoint indicates an expected call of ListEdgeClustersEndpoint.
func (mr *MockEndpointCreatorContractMockRecorder) ListEdgeClustersEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEdgeClustersEndpoint", reflect.TypeOf((*MockEndpointCreatorContract)(nil).ListEdgeClustersEndpoint))
}

// ReadEdgeClusterEndpoint mocks base method.
func (m *MockEndpointCreatorContract) ReadEdgeClusterEndpoint() endpoint.Endpoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadEdgeClusterEndpoint")
	ret0, _ := ret[0].(endpoint.Endpoint)
	return ret0
}

// ReadEdgeClusterEndpoint indicates an expected call of ReadEdgeClusterEndpoint.
func (mr *MockEndpointCreatorContractMockRecorder) ReadEdgeClusterEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadEdgeClusterEndpoint", reflect.TypeOf((*MockEndpointCreatorContract)(nil).ReadEdgeClusterEndpoint))
}

// UpdateEdgeClusterEndpoint mocks base method.
func (m *MockEndpointCreatorContract) UpdateEdgeClusterEndpoint() endpoint.Endpoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEdgeClusterEndpoint")
	ret0, _ := ret[0].(endpoint.Endpoint)
	return ret0
}

// UpdateEdgeClusterEndpoint indicates an expected call of UpdateEdgeClusterEndpoint.
func (mr *MockEndpointCreatorContractMockRecorder) UpdateEdgeClusterEndpoint() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEdgeClusterEndpoint", reflect.TypeOf((*MockEndpointCreatorContract)(nil).UpdateEdgeClusterEndpoint))
}
